### ISSUE TITLE
CS2 instant crash

### ISSUE THREAD

**Issue by ECDSA-code** [neverlosecc/source2gen#10]
hello folks. the process crashes immediately after loading the dll into the process, any fix available?

**Comment by es3n1n** [comment]
Hey, it is probably due to the recent cs2 updates. You should update the offsets/indexes for the newest version, you can also open a pr for it. We don't have much time to update this project :shrug:

**Comment by es3n1n** [comment]
Fixed in https://github.com/neverlosecc/source2gen/commit/6b73085d9ae3111cb672f491907fee6c195eaa31
