### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Sigma12456** [neverlosecc/source2gen#16]

**Comment by cpz** [comment]
If you have experience coding, you'll understand. I will only respond once to such issue, then just close them. 


1. Download premake5. 
2. Navigate to the cloned repository folder in the command prompt and enter 'premake5 vs2022' and then open the project in Visual Studio 2022.
3. Compile the code.
4. Inject compiled DLL into the game to generate SDK.
5. And now you have created the SDK. The SDK can be found in the folder where the game's .exe file is located.

**Comment by lintangtimur** [comment]
ok got it, im confused where the sdk generated, now i found it coz reading this issue. ty
