### ISSUE TITLE
generated option

### ISSUE THREAD

**Issue by lintangtimur** [neverlosecc/source2gen#18]
Hello, thank you for this project. It's been very helpful with its output and the references provided. Is there an option to generate the output in various formats, for example, JSON, CS, or something simpler? I've seen references in other repositories where the dump results are more straightforward. For example:

CS2: https://github.com/a2x/cs2-dumper
Dota 2: https://github.com/ikhsanprasetyo/dota2dumped
Their output includes .hpp, .cs, .json, .rs formats.

Thank you.

**Comment by es3n1n** [comment]
Hello, no, there's no such options and such features were never really planned, but we may take a look into it someday (no eta sorry, i'm quite busy with some personal projects)
