### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by saul** [neverlosecc/source2gen#19]
Hi - what is this code licensed under? I'd like to fork it for CS2 reverse engineering purposes.

Many thanks

**Comment by es3n1n** [comment]
Hey and sorry, we completely forgot about the license. 1063e42a9e25e4b290e52d0222bf33b3c6b4fb10

**Comment by saul** [comment]
Many thanks for the quick update. One question - the underlying library that you forked from is [MIT licensed](https://github.com/praydog/Source2Gen/blob/master/LICENSE.md). I believe it requires that license acknowledged in your copy (this is how I did it: https://github.com/saul/CS2SchemaGen/blob/main/ACKNOWLEDGEMENTS)

**Comment by cpz** [comment]
> Many thanks for the quick update. One question - the underlying library that you forked from is [MIT licensed](https://github.com/praydog/Source2Gen/blob/master/LICENSE.md). I believe it requires that license acknowledged in your copy (this is how I did it: https://github.com/saul/CS2SchemaGen/blob/main/ACKNOWLEDGEMENTS)

Thank you very much! We did what you said, it took a bit more time as I was doing some reverse for schema at the time.
