### ISSUE TITLE
Consider getting rid of the premake5 in favor of cmake

### ISSUE THREAD

**Issue by es3n1n** [neverlosecc/source2gen#22]
that's pretty much it

**Comment by cpz** [comment]
why tho, premake ftw kiddo

**Comment by kehrazy** [comment]
> why tho, premake ftw kiddo

because vendorlocking yourself to msvc/visual studio is the fastest way to get a free visit to the nearby mental institution

**Comment by cpz** [comment]
> > why tho, premake ftw kiddo
> 
> because vendorlocking yourself to msvc/visual studio is the fastest way to get a free visit to the nearby mental institution

livin in mental institution since 2k7 and lovin it

> would actually take this if nobody wants to do this

It would be great

**Comment by kehrazy** [comment]
basic support added by #37
