### ISSUE TITLE
Fix output metadata string for MResourceTypeForInfoType

### ISSUE THREAD

**Issue by cpz** [neverlosecc/source2gen#25]
E.g: https://github.com/neverlosecc/source2sdk/blob/dota/sdk/resourcesystem.hpp#L605
Related code: https://github.com/neverlosecc/source2gen/blob/main/src/sdk/sdk.cpp#L115

**Comment by es3n1n** [comment]
The main reason we are getting these "random" bytes is that the size of this value isn't always a 32/16-byte value. Instead, it could be only 8 bytes in length and its value could be fit without the null terminator.
![image](https://github.com/neverlosecc/source2gen/assets/40367813/81a687d5-c73d-4d06-bb8c-a5048e7629ea)

And now the question I don't have the answer to(for now): Where should we get the reserved size instead? Probably the reversals of how this stuff gets allocated in heap could help us with answering this question.

**Comment by es3n1n** [comment]
Reopening because this issue isn't fully resolved and we still have a bunch of inconsistent strings.
