### ISSUE TITLE
tier0 not loaded when attempting to generate Deadlock SDK.

### ISSUE THREAD

**Issue by Electron7-7** [neverlosecc/source2gen#63]
Full disclosure: it's 1:10AM and my adhd meds are completely worn off. I wanna mod Deadlock because I think that sounds funny and my autism caused me to spend hours going down rabbit holes related to Source 2. Long story short: I built the binaries, used the DEADLOCK flag, ran source2gen-loader.exe and got a folder named 'sdk', and I didn't know what to do with it, so I tried running source2gen.exe. When I did, it told me it couldn't load the module "tier0" and aborted. I dug through the source code but, frankly, I don't know enough C++ yet to fully understand what I'm even trying to do. Hell, I don't even know what I'm trying to get here. Something to be able to use the janky HL:A tools to make a crappy Deadlock mod or something, I guess. Anyways, feel free to chuck this out if it's a total bone-headed non-issue. Just thought I'd say something rather than nothing. Y'all do God's work. (oh, also.... i have no clue how to even use a generated sdk. My dumbass thinks it'll just compile magically into an exe. I highly doubt that's the intended use of this tool, now that I'm thinking about it. You know, submitting this is probably gonna be embarrassing for me in hindsight but it's better than same old same old. Yeesh, I'm gonna go to bed)

**Comment by cpz** [comment]
Since deadlock is still not released yet, there may be situations where it will not be added by steam to the Steam\steamapps\libraryfolders.vdf file on Windows. So you need to open it with any editor and add to it manually 
![image](https://github.com/user-attachments/assets/32cd9a69-b23c-42b1-a13d-85fd9920652d)

As shown in the screenshot (this is just an example). 

What you need to add is ‘1422450’ ‘1334’, 1334 you can change to any variable you already have, for example copy it from 730 or any other game.

**Comment by es3n1n** [comment]
Ha, what a fun story. 
You don't need to launch source2gen.exe, all you need to launch is source2gen-loader and it will generate the SDK in the sdk folder, just as you said. The comment below is wrong.
As for what to do with the generated SDK - I think it's up to you as we're only providing tool for generating these SDKs. 
I would recommend you first get some sleep, then take your adhd meds, and then figure out what do you want to mod exactly. Please reopen this issue if you need any further help and make sure to include what's wrong exactly.

**Comment by es3n1n** [comment]
Although I must admit that, judging by the way this issue was written, I believe your adhd meds might've still been working at that time

**Comment by artemking4** [comment]
Actually quite the other way around: those meds simply make dopamine stay in the brain for longer, increasing attention/concentration... Well, judging by his text, he has quite a severe case of ADHD and his meds sure as hell wore off completely, lol
