### ISSUE TITLE
How to use generated sdk?

### ISSUE THREAD

**Issue by strainxx** [neverlosecc/source2gen#65]
When i include any header and build project i get 100+ errors
![image](https://github.com/user-attachments/assets/a6ddb63c-d67b-46c5-a391-5c726cd6e490)
![image](https://github.com/user-attachments/assets/de6552b6-7d76-4deb-8990-e79ad7d341e0)
Sorry for stupid question but how to use it?

**Comment by es3n1n** [comment]
Hi, the currently generated SDKs cannot be compiled. The only version of source2gen that outputs a compilable SDK is at #62, but it hasn’t been merged yet (it will be merged in a few days)

**Comment by es3n1n** [comment]
FIxed in https://github.com/neverlosecc/source2gen/commit/209b85c7ab520a5644736a209356463b81cac1b0
