### ISSUE TITLE
Errors while generating SDK (Deadlock)

### ISSUE THREAD

**Issue by null-lnp** [neverlosecc/source2gen#67]
Got the following errors whilst trying to generate SDK for Deadlock.
(image below)

Steps were done as instructed on readme.
For more context, it outputs the folder **_sdk_** with includes and generated classes, but it seems incomplete (when comparing with other generated SDKs)

![image (2)](https://github.com/user-attachments/assets/7bbff395-b5e1-4835-855b-9eea75a43fbf)

**Comment by es3n1n** [comment]
Oh wow, at first glance this looks like a bug introduced by the game. Can you be more precise on what version you are running the tool?

**Comment by noel-debug** [comment]
![image](https://github.com/user-attachments/assets/173cf474-03a9-4c80-ae5c-ce230a3eab51)
happens for me on this version (latest) as well

**Comment by es3n1n** [comment]
Can confirm that this *sometimes* happens on the latest deadlock build, the only thing I can suggest for now is to retry a few times - on @cpz's machine it works half of the time. But yeah, we'll look into this in a few days.

**Comment by null-lnp** [comment]
> Can confirm that this _sometimes_ happens on the latest deadlock build, the only thing I can suggest for now is to retry a few times - on @cpz's machine it works half of the time. But yeah, we'll look into this in a few days.

Keep on retrying until it decides to work? Alright, I can do that. Thank you for the quick reply.

**Comment by es3n1n** [comment]
> Keep on retrying until it decides to work? Alright, I can do that. Thank you for the quick reply.

Yeah, sorry. This is the best solution we have for now as we're still looking into this issue 🫡

**Comment by noel-debug** [comment]
Not sure if this is any helpful. But the issue always appears inside of GenerateEnumSdk when trying to generate for "EModifierValue". As soon as you skip that it works just fine.

**Comment by noel-debug** [comment]
Oh I was just writing the reason for the bug as comment but I guess you were faster.
Thanks for the quick support :D

**Comment by es3n1n** [comment]
Yup! Can you guys please try again now with the latest changes? 
cc @noel-debug @null-lnp

**Comment by noel-debug** [comment]
Works like a charm
