### ISSUE TITLE
credits?

### ISSUE THREAD

**Issue by recoil24** [neverlosecc/source2gen#70]
i am sorry to ruin your party
https://github.com/praydog/Source2Gen
:)

**Comment by Cre3per** [comment]
Praydog reversed the schema system and wrote an article about it on https://praydog.com/reverse-engineering/2015/06/24/source2.html  
The original project was archived in 2023 and development continued here. Praydog is listed in [the credits](https://github.com/neverlosecc/source2gen?tab=readme-ov-file#credits) as the original author of Source2Gen.
