### ISSUE TITLE
hmm dota 2 crashed.

### ISSUE THREAD

**Issue by TomieAi** [neverlosecc/source2gen#8]
Tried GH Injector / and other Manual Map it just crashed.. am I missing something? what injector you guys recommend? 

I just saw the 
![image](https://user-images.githubusercontent.com/111332073/230698754-79de9141-8960-4686-b059-8351809684be.png)
then it crash after 2 seconds. sdk folder still empty

**Comment by es3n1n** [comment]
did you update the game definition in schema.h?
https://github.com/neverlosecc/source2gen#update-the-game-definition

**Comment by TomieAi** [comment]
nvm my bad and im sorry. i build the dll manually instead of relying on the premake script u guys made.. sorry i close this now
